### ISSUE TITLE
评论支持joke和emotion类型，增加评论置顶

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/jx3box-comment-ui#20]
## 评论支持joke和emotion类型
原先joke和emotion是在wp_posts表中的，要更换。
已独立在主库的 pvx_emotions和pvx_jokes表中。

【主ISSUE】https://github.com/JX3BOX/jx3box-comment-ui/issues/9
更新如下：
![image](https://user-images.githubusercontent.com/8476969/145705713-925b0678-a3aa-4408-8393-d79a64ad66e4.png)

新增支持2个对应的评论类型

**Comment by iRuxu** [comment]
## 评论新增置顶功能
### 1.评论条目中增加置顶按钮 
![image](https://user-images.githubusercontent.com/8476969/145705765-df98131d-50e5-4c6c-834e-2fc6cf0e90f2.png)
+ 仅原作者可用
+ 图标：el-icon-top

### 2.工具栏改版
![image](https://user-images.githubusercontent.com/8476969/145705992-e26c1fef-1dc4-4938-b6cf-5d2037f8be0b.png)
+ 排序模式改为按钮组 https://element.eleme.cn/#/zh-CN/component/radio

### 3.评论列表
+ 
+ 


+ 当评论显示时，默认优先显示置顶的评论。

**Comment by iRuxu** [comment]
在周三/四前完成

**Comment by flyflyknife** [comment]
> ## 评论支持joke和emotion类型
> 原先joke和emotion是在wp_posts表中的，要更换。 已独立在主库的 pvx_emotions和pvx_jokes表中。
> 
> 【主ISSUE】#9 更新如下： ![image](https://user-images.githubusercontent.com/8476969/145705713-925b0678-a3aa-4408-8393-d79a64ad66e4.png)
> 
> 新增支持2个对应的评论类型

完成待上线

**Comment by iRuxu** [comment]
## 置顶权限问题。

![image](https://user-images.githubusercontent.com/8476969/146406637-fccdfd71-7d22-4445-a2a4-a20318f8bea3.png)
http://localhost:8081/api/comment/post/article/100/i-am-author
我是管理员，接口返回中有权限

但是实际操作时，如下：
![image](https://user-images.githubusercontent.com/8476969/146406568-9702357c-fb07-42f2-b913-b1e90624c389.png)

- [ ] 已完成

**Comment by flyflyknife** [comment]
> ## 置顶权限问题。
> ![image](https://user-images.githubusercontent.com/8476969/146406637-fccdfd71-7d22-4445-a2a4-a20318f8bea3.png) http://localhost:8081/api/comment/post/article/100/i-am-author 我是管理员，接口返回中有权限
> 
> 但是实际操作时，如下： ![image](https://user-images.githubusercontent.com/8476969/146406568-9702357c-fb07-42f2-b913-b1e90624c389.png)
> 
> * [ ]  已完成

这里所以显示bug，你不是作者不应该展示这个

![image](https://user-images.githubusercontent.com/68375170/146629314-6e59209b-7c9c-4ddf-9eb3-17f2f0462ee4.png)

**Comment by flyflyknife** [comment]
已更新 需要重新上线前端

**Comment by iRuxu** [comment]
置顶的仍然有错误。
我现在是19382的作者
![image](https://user-images.githubusercontent.com/8476969/146676788-769111be-2b0b-46be-9e50-6fbe33d88246.png)
这里返回的却是100
