### ISSUE TITLE
新增评论短消息模板

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/jx3box-comment-ui#23]
![image](https://user-images.githubusercontent.com/8476969/158309186-94a05802-8102-4278-b110-41fa22a84a99.png)

该应用即将上线，评论需要配置
如已配置，请直接回复并关闭issue即可

**Comment by flyflyknife** [comment]
一配置，见 JX3BOX/jx3box-api 2e4806b3dfc7f0a1a56ab6e9384b8a85e39ff87e
