### ISSUE TITLE
胧月反馈作者查看时的bug

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/jx3box-comment-ui#24]
胧月 2022/5/1 16:42:43
帖子作者回复评论后不予显示

浮烟 2022/5/1 16:49:53
啥意思

胧月 2022/5/1 16:55:00
你写了一篇帖子，我下去评论你，你回复我的评论后，我看不到你的回复

胧月 2022/5/1 16:55:03
你也看不到你的回复

浮烟 2022/5/1 16:55:57
其他情况呢

胧月 2022/5/1 16:56:34
一个评论多个回复的时候，不显示作者的回复，只有点击查看更多才会显示

胧月 2022/5/1 16:56:46
只有作者有这个问题

胧月 2022/5/1 16:57:11
https://origin.jx3box.com/macro/18608

胧月 2022/5/1 16:57:21
这个帖子下面所有 我的回复都没有显示

浮烟 2022/5/1 16:58:30
之前都正常是吧

胧月 2022/5/1 16:58:44
新赛季更新后出现的

胧月 2022/5/1 16:59:31
不过更新当天有显示，4.29只有4.28那天我回复的内容显示了，4.30就全都不显示了

**Comment by M-ls** [comment]
补充：
https://www.jx3box.com/tool/32476 此链接下部分长回复处于折叠状态时
![9PJJ5WN16GOO55Q10_8DQJY](https://user-images.githubusercontent.com/36070993/166140601-c00d314d-2616-431c-b0c9-11c722bec729.png)
点击“查看更多”后可正常加载
![image](https://user-images.githubusercontent.com/36070993/166140636-838dc294-3b49-4027-a833-ce117fa9e498.png)
