### ISSUE TITLE
评论增加附件支持

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/jx3box-comment-ui#3]
评论中支持插入图片（方便反馈bug之类）。
上传接口可以使用 server.jx3box.com/upload（需携带token）
插入的图片，默认使用一个缩略图列表，点击图片灯箱效果显示原图。
缩略图使用图片添加 图片路径+`?x-oss-process=style/comment_thumb` 即可为显示缩略图
同时可以考虑增加一个markdown编辑器，支持简单的渲染

**Comment by flyflyknife** [comment]
是否可以使用文章的markdown编辑器?

**Comment by iRuxu** [comment]
文章目前是tinymce编辑器，较为庞大。评论部分建议使用一个非常简单的markdown编辑器即可，参考github当前的状态。

**Comment by iRuxu** [comment]
如开发成本较高，可以不做编辑器支持，只需要支持附件即可

**Comment by flyflyknife** [comment]
请使用　next.jx3box.com 域名进行测试，，　css可能需要进行调整
