### ISSUE TITLE
评论点赞

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/jx3box-comment-ui#32]
![f31fb0b19625557627a5152e35e763a1](https://github.com/JX3BOX/jx3box-comment-ui/assets/8476969/d0371661-ea60-45f7-bdaf-b4f3c5171f4f)

优化样式出具示意图

**Comment by iRuxu** [comment]
1.不开启时，红色改灰色，开启则是蓝色。默认不开启。

2.点赞图标换一个svg图标，自己找一下替换下（自己看下他代码要不要区分已点和没点，需要的话找胧月或南宫伯支持两个图）

3.目前【置顶】【精华】的操作按钮不见了（在回复边上）

![d0eac8449e9a96a5b1c71c11395b7fa4](https://github.com/JX3BOX/jx3box-comment-ui/assets/8476969/51d48f76-56b1-41d3-9268-2cc00025193d)


但是小胡说他有jia'j加精，也没有置顶。看看代码到底之前改了什么，需要恢复。

**Comment by Kaviilee** [comment]
> 1.不开启时，红色改灰色，开启则是蓝色。默认不开启。
> 
> 2.点赞图标换一个svg图标，自己找一下替换下（自己看下他代码要不要区分已点和没点，需要的话找胧月或南宫伯支持两个图）
> 
> 3.目前【置顶】【精华】的操作按钮不见了（在回复边上）
> 
> ![d0eac8449e9a96a5b1c71c11395b7fa4](https://user-images.githubusercontent.com/8476969/258829810-51d48f76-56b1-41d3-9268-2cc00025193d.png)
> 
> 但是小胡说他有jia'j加精，也没有置顶。看看代码到底之前改了什么，需要恢复。

置顶需要帖子本人才能置顶
