### ISSUE TITLE
短消息跳转扩展

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/jx3box-comment-ui#38]
## 模型

<img width="1017" alt="image" src="https://github.com/JX3BOX/jx3box-comment-ui/assets/8476969/1d0e1776-add0-4929-8575-0a5aadabe55e">

现在短消息表是有一个跳转字段的

- [x] 已完成

**Comment by iRuxu** [comment]
## 历史背景

以前我们是通过source_type和source_id来自动组合跳转的地址。
但是比如我们新开的作业评论模式
https://www.jx3box.com/tool/80317
<img width="1369" alt="image" src="https://github.com/JX3BOX/jx3box-comment-ui/assets/8476969/f662f0e3-88da-428d-a07e-8a10ee95dbc4">

这里的source_type和id肯定还是要写评论本身的id的。
所以跳转需要另外设置。

需要让评论组件支持redirect参数，并提交到后端。

个人消息页面会优先判断redirect，如果不存在则会沿用原规则，如果存在会优先用redirect的链接

- [ ] 已完成

**Comment by flyflyknife** [comment]
![图片](https://github.com/JX3BOX/jx3box-comment-ui/assets/68375170/26b6992e-c9ca-4925-9c40-0c9225e2548a)
