### ISSUE TITLE
评论系统扩展性优化

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/jx3box-comment-ui#4]
目前仅可用于主cms，需要对表进行扩展，以支持其它项目。
例如可以对某个趣味题库的题目进行讨论、试卷讨论、后续独立的表情栏目和剑三百科栏目。
都需要新增对应的讨论功能

**Comment by iRuxu** [comment]
可以考虑新建一个表来实现cms之外的内容（比如题库，百科）

**Comment by flyflyknife** [comment]
在当前表中增加一个字段用来标识不同类型即可实现, 无需维护两套评论系统

**Comment by flyflyknife** [comment]
```
<Comment id="100" category="post"/>
```
// id 分类下的主键id, 比如　，如果该评论属于文章，那么id 应该为　文章的id, 如果该评论为试卷的评论，那么该id 应该为试卷的id
// category 评论所属分类，比如　文章，试卷，试题，百科等．
// 为了对消息通知有好， 一般消息wp_messages表中的sourceType需要什么就填什么，［文章除外，文章类型使用　'post', 服务器会进行处理，需要二次查询文章具体类别］
//　比如对于试卷的评论组件，comments表中的sourceType需要的是 paper 那么　category="paper"
请在　next.jx3box.com 下进行测试
